### ISSUE TITLE
Add documentation for how to test a project that uses simple-env

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/simple-env#20]
### Pre-requisites:

- [x] Yes, I looked through both [open and closed issues](../../../issues?utf8=✓&q=is%3Aissue) looking for what I needed

## Feature Description

When a user incorporates `simple-env` within their project, tests can get complicated and might fail in CI pipelines. We should add some documentation to show users how to best test the project via jest.

**Comment by johnkahn** [comment]
@SpencerKaiser Can you read this in the notification?

**Comment by SpencerKaiser** [comment]
@johnkahn did you get a notification for this?

**Comment by johnkahn** [comment]
@SpencerKaiser Did you get notified?

**Comment by SpencerKaiser** [comment]
@johnkahn sure did! How about you?

**Comment by SpencerKaiser** [comment]
@johnkahn make sure to include documentation for how to use the `__mocks__` directory
